Added leading underscore as required by OSX
SINTEF/thermopack pull request #29
Opened 2022-01-19 20:23 UTC by morteham

2022-01-20 09:53 UTC, vegardjervell commented
This compiled and installed with pip as expected, but left some warnings from the linker. I have to admit, I'm not experienced enough to assess whether it's safe to ignore them, this is the log:

```
gmake FC=gfortran MODE=optim FFLAGS="-cpp -fPIC -fdefault-real-8 -fdefault-double-8 -O3 -march=x86-64 -msse2 -funroll-loops" CFLAGS= TARGET=optim_gfortran_Darwin LEXT=gfortran_Darwin -f Makefile.code -e thermopack
gmake[1]: Entering directory '/Users/vegardjervell/Documents/GitHub/thermopack'
gmake -f Makefile.code -e trend_optim_gfortran_Darwin
gmake[2]: Entering directory '/Users/vegardjervell/Documents/GitHub/thermopack'
gmake[2]: Nothing to be done for 'trend_optim_gfortran_Darwin'.
gmake[2]: Leaving directory '/Users/vegardjervell/Documents/GitHub/thermopack'
gmake -f Makefile.code -e libthermopack_optim_gfortran_Darwin.a
gmake[2]: Entering directory '/Users/vegardjervell/Documents/GitHub/thermopack'
/usr/bin/ar -r -c ./bin/libthermopack_optim_gfortran_Darwin.a ./objects/optim_gfortran_Darwin/numconstants.o ./objects/optim_gfortran_Darwin/stringmod.o ./objects/optim_gfortran_Darwin/quadratures.o ./objects/optim_gfortran_Darwin/thermopack_constants.o ./objects/optim_gfortran_Darwin/error.o ./objects/optim_gfortran_Darwin/optimizer.o ./objects/optim_gfortran_Darwin/nonlinear_solvers.o ./objects/optim_gfortran_Darwin/utilities.o ./objects/optim_gfortran_Darwin/apparent_composition.o ./objects/optim_gfortran_Darwin/compdata.o ./objects/optim_gfortran_Darwin/association_var.o ./objects/optim_gfortran_Darwin/thermopack_var.o ./objects/optim_gfortran_Darwin/compdatadb.o ./objects/optim_gfortran_Darwin/compdata_init.o ./objects/optim_gfortran_Darwin/multiparameter_base.o ./objects/optim_gfortran_Darwin/multiparameter_c3.o ./objects/optim_gfortran_Darwin/multiparameter_para_h2.o ./objects/optim_gfortran_Darwin/multiparameter_ortho_h2.o ./objects/optim_gfortran_Darwin/multiparameter_normal_h2.o ./objects/optim_gfortran_Darwin/multiparameter_r134a.o ./objects/optim_gfortran_Darwin/mbwrdata.o ./objects/optim_gfortran_Darwin/mbwr.o ./objects/optim_gfortran_Darwin/mbwr_additional.o ./objects/optim_gfortran_Darwin/pets.o ./objects/optim_gfortran_Darwin/eosdata.o ./objects/optim_gfortran_Darwin/assocschemeutils.o ./objects/optim_gfortran_Darwin/pc_saft_parameters.o ./objects/optim_gfortran_Darwin/unifacdata.o ./objects/optim_gfortran_Darwin/unifac.o ./objects/optim_gfortran_Darwin/eos_parameters.o ./objects/optim_gfortran_Darwin/cubic_eos.o ./objects/optim_gfortran_Darwin/mixdatadb.o ./objects/optim_gfortran_Darwin/cbalpha.o ./objects/optim_gfortran_Darwin/cbbeta.o ./objects/optim_gfortran_Darwin/excess_gibbs.o ./objects/optim_gfortran_Darwin/wong_sandler.o ./objects/optim_gfortran_Darwin/cbmix.o ./objects/optim_gfortran_Darwin/cbhelm.o ./objects/optim_gfortran_Darwin/cubic.o ./objects/optim_gfortran_Darwin/idealh2.o ./objects/optim_gfortran_Darwin/ideal.o ./objects/optim_gfortran_Darwin/cpa_parameters.o ./objects/optim_gfortran_Darwin/cbselect.o ./objects/optim_gfortran_Darwin/pc_saft_nonassoc.o ./objects/optim_gfortran_Darwin/saftvrmie_options.o ./objects/optim_gfortran_Darwin/saftvrmie_parameters.o ./objects/optim_gfortran_Darwin/saftvrmie_containers.o ./objects/optim_gfortran_Darwin/saftvrmie_utils.o ./objects/optim_gfortran_Darwin/saftvrmie_hardsphere.o ./objects/optim_gfortran_Darwin/saftvrmie_dispersion.o ./objects/optim_gfortran_Darwin/saftvrmie_chain.o ./objects/optim_gfortran_Darwin/saftvrmie_interface.o ./objects/optim_gfortran_Darwin/saft_globals.o ./objects/optim_gfortran_Darwin/saft_rdf.o ./objects/optim_gfortran_Darwin/saft_association.o ./objects/optim_gfortran_Darwin/saft_interface.o ./objects/optim_gfortran_Darwin/extcsp.o ./objects/optim_gfortran_Darwin/leekesler.o ./objects/optim_gfortran_Darwin/multiparameter_idealmix.o ./objects/optim_gfortran_Darwin/volume_shift.o ./objects/optim_gfortran_Darwin/co2_gibbs.o ./objects/optim_gfortran_Darwin/h2o_gibbs.o ./objects/optim_gfortran_Darwin/single_component.o ./objects/optim_gfortran_Darwin/eos_container.o ./objects/optim_gfortran_Darwin/single_phase.o ./objects/optim_gfortran_Darwin/eostv.o ./objects/optim_gfortran_Darwin/trend_solver.o ./objects/optim_gfortran_Darwin/eos.o ./objects/optim_gfortran_Darwin/puresaturation.o ./objects/optim_gfortran_Darwin/thermo_utils.o ./objects/optim_gfortran_Darwin/critical.o ./objects/optim_gfortran_Darwin/saturation.o ./objects/optim_gfortran_Darwin/solideos.o ./objects/optim_gfortran_Darwin/vls.o ./objects/optim_gfortran_Darwin/stability.o ./objects/optim_gfortran_Darwin/tuning.o ./objects/optim_gfortran_Darwin/tp_solver.o ./objects/optim_gfortran_Darwin/state_functions.o ./objects/optim_gfortran_Darwin/saturation_curve.o ./objects/optim_gfortran_Darwin/solid_saturation.o ./objects/optim_gfortran_Darwin/saturation_point_locators.o ./objects/optim_gfortran_Darwin/ph_solver.o ./objects/optim_gfortran_Darwin/ps_solver.o ./objects/optim_gfortran_Darwin/uv_solver.o ./objects/optim_gfortran_Darwin/sv_solver.o ./objects/optim_gfortran_Darwin/isolines.o ./objects/optim_gfortran_Darwin/binaryplot.o ./objects/optim_gfortran_Darwin/speed_of_sound.o ./objects/optim_gfortran_Darwin/saftvrmie_testing.o ./objects/optim_gfortran_Darwin/consistency.o ./objects/optim_gfortran_Darwin/eoslibinit.o ./objects/optim_gfortran_Darwin/complexmodelinit.o ./objects/optim_gfortran_Darwin/external.o ./objects/optim_gfortran_Darwin/dltrend_dummy.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./bin/libthermopack_optim_gfortran_Darwin.a(numconstants.o) has no symbols
/usr/bin/ranlib ./bin/libthermopack_optim_gfortran_Darwin.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ./bin/libthermopack_optim_gfortran_Darwin.a(numconstants.o) has no symbols
gmake[2]: Leaving directory '/Users/vegardjervell/Documents/GitHub/thermopack'
gmake[2]: Entering directory '/Users/vegardjervell/Documents/GitHub/thermopack'
gfortran -shared -o ./bin/dynamic/libthermopack_optim_gfortran_Darwin.dynlib ./objects/optim_gfortran_Darwin/numconstants.o ./objects/optim_gfortran_Darwin/stringmod.o ./objects/optim_gfortran_Darwin/quadratures.o ./objects/optim_gfortran_Darwin/thermopack_constants.o ./objects/optim_gfortran_Darwin/error.o ./objects/optim_gfortran_Darwin/optimizer.o ./objects/optim_gfortran_Darwin/nonlinear_solvers.o ./objects/optim_gfortran_Darwin/utilities.o ./objects/optim_gfortran_Darwin/apparent_composition.o ./objects/optim_gfortran_Darwin/compdata.o ./objects/optim_gfortran_Darwin/association_var.o ./objects/optim_gfortran_Darwin/thermopack_var.o ./objects/optim_gfortran_Darwin/compdatadb.o ./objects/optim_gfortran_Darwin/compdata_init.o ./objects/optim_gfortran_Darwin/multiparameter_base.o ./objects/optim_gfortran_Darwin/multiparameter_c3.o ./objects/optim_gfortran_Darwin/multiparameter_para_h2.o ./objects/optim_gfortran_Darwin/multiparameter_ortho_h2.o ./objects/optim_gfortran_Darwin/multiparameter_normal_h2.o ./objects/optim_gfortran_Darwin/multiparameter_r134a.o ./objects/optim_gfortran_Darwin/mbwrdata.o ./objects/optim_gfortran_Darwin/mbwr.o ./objects/optim_gfortran_Darwin/mbwr_additional.o ./objects/optim_gfortran_Darwin/pets.o ./objects/optim_gfortran_Darwin/eosdata.o ./objects/optim_gfortran_Darwin/assocschemeutils.o ./objects/optim_gfortran_Darwin/pc_saft_parameters.o ./objects/optim_gfortran_Darwin/unifacdata.o ./objects/optim_gfortran_Darwin/unifac.o ./objects/optim_gfortran_Darwin/eos_parameters.o ./objects/optim_gfortran_Darwin/cubic_eos.o ./objects/optim_gfortran_Darwin/mixdatadb.o ./objects/optim_gfortran_Darwin/cbalpha.o ./objects/optim_gfortran_Darwin/cbbeta.o ./objects/optim_gfortran_Darwin/excess_gibbs.o ./objects/optim_gfortran_Darwin/wong_sandler.o ./objects/optim_gfortran_Darwin/cbmix.o ./objects/optim_gfortran_Darwin/cbhelm.o ./objects/optim_gfortran_Darwin/cubic.o ./objects/optim_gfortran_Darwin/idealh2.o ./objects/optim_gfortran_Darwin/ideal.o ./objects/optim_gfortran_Darw [...]

2022-01-21 12:14 UTC, vegardjervell commented
When testing the python-interface I'm getting an error from `libgfortran.5.dylib` saying it can't find `libquadmath.0.dylib`, even though the file is at the expected path, but I believe this has something to do with my file system, not Thermopack.

Running 
```
from pyctp import cubic
eos = cubic.cubic()
```
Gives the traceback:
```
Traceback (most recent call last):
  File "/Users/vegardjervell/Documents/master/model/test.py", line 3, in <module>
    eos = cubic.cubic()
  File "/Users/vegardjervell/Documents/master/model/venv/lib/python3.9/site-packages/pyctp/cubic.py", line 25, in __init__
    super(cubic, self).__init__()
  File "/Users/vegardjervell/Documents/master/model/venv/lib/python3.9/site-packages/pyctp/thermo.py", line 30, in __init__
    self.tp = cdll.LoadLibrary(dyn_lib_path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/vegardjervell/Documents/master/model/venv/lib/python3.9/site-packages/pyctp/libthermopack.dynlib, 6): Library not loaded: /usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libquadmath.0.dylib
  Referenced from: /usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib
  Reason: image not found
Exception ignored in: <function thermopack.__del__ at 0x110f00c10>
Traceback (most recent call last):
  File "/Users/vegardjervell/Documents/master/model/venv/lib/python3.9/site-packages/pyctp/thermo.py", line 116, in __del__
    self.delete_eos()
  File "/Users/vegardjervell/Documents/master/model/venv/lib/python3.9/site-packages/pyctp/thermo.py", line 132, in delete_eos
    self.activate()
  File "/Users/vegardjervell/Documents/master/model/venv/lib/python3.9/site-packages/pyctp/thermo.py", line 120, in activate
    self.s_activate_model.argtypes = [POINTER( c_int )]
AttributeError: 'cubic' object has no attribute 's_activate_model'
```
I've checked that the file `/usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libquadmath.0.dylib` exists. I'm still looking into it to see if the issue is on my side, rather than with thermopack.

2022-01-21 13:53 UTC, vegardjervell commented
Update: There was an issue with my gcc installation, the path `/usr/local/Cellar/gcc/11.2.0/` had somehow become `/usr/local/Cellar/gcc/11.2.0.reinstall/`, so just made a soft link from `11.2.0` to `11.2.0.reinstall`. Now i get a segfault on line 3 when running
```
from pyctp import cubic
eos = cubic.cubic()
eos.init('NC5,NC10', 'SRK')
```
That is, the first two lines run, but introducing the third line produces a segfault from the `libgfortran.5.dylib`-thread, crash-report below. I don't understand how this should be related to an issue with my files, but I can try cleaning and reinstalling gcc and gfortran to make sure.

```
Process:               Python [61061]
Path:                  /opt/local/Library/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.9.2 (3.9.2)
Code Type:             X86-64 (Native)
Parent Process:        bash [56029]
Responsible:           Python [61061]
User ID:               501

Date/Time:             2022-01-21 14:34:58.974 +0100
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Anonymous UUID:        291263B5-560A-0711-8E66-E13079E079BB

Sleep/Wake UUID:       4541C99A-BE55-4320-9BA4-0DCD3706A66D

Time Awake Since Boot: 990000 seconds
Time Since Wake:       5500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fff11691112
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [61061]

VM Regions Near 0x7fff11691112:
    Stack                  00007ffee7127000-00007ffee8127000 [ 16.0M] rw-/rwx SM=ALI  thread 0
--> Submap                 00007fff00000000-00007fff80000000 [  2.0G] r--/rwx SM=SHM  machine-wide VM submap
    unused shlib __TEXT    00007fff32cd1000-00007fff3b339000 [134.4M] r-x/r-x SM=COW  system shared lib __TEXT not used by this process

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libgfortran.5.dylib           	0x0000000112527d69 _gfortran_string_len_trim.part.0 + 137
1   libthermopack.dynlib          	0x0000000111d183cd __eoslibinit_MOD_init_cubic + 765
2   libffi.7.dylib                	0x00000001081bcef5 ffi_call_unix64 + 85
3   libffi.7.dylib                	0x00000001081bc7fd ffi_call_int + 704
4   _ctypes.cpython-39-darwin.so  	0x000000010819f98e _ctypes_callproc + 843
5   _ctypes.cpython-39-darwin.so  	0x000000010819a3c5 PyCFuncPtr_call + 1014
6   org.python.python             	0x0000000107b14f75 _PyObject_MakeTpCall + 266
7   org.python.python             	0x0000000107bbcd3d call_function + 451
8   org.python.python             	0x0000000107bb5dbd _PyEval_EvalFrameDefault + 6971
9   org.python.python             	0x0000000107bbd805 _PyEval_EvalCode + 1911
10  org.python.python             	0x0000000107b155c2 _PyFunction_Vectorcall + 249
11  org.python.python             	0x0000000107bbcd09 call_function + 399
12  org.python.python             	0x0000000107bb5d9e _PyEval_EvalFrameDefault + 6940
13  org.python.python             	0x0000000107bbd805 _PyEval_EvalCode + 1911
14  org.python.python             	0x0000000107bb41c0 PyEval_EvalCode + 66
15  org.python.python             	0x0000000107beef2f run_eval_code_obj + 110
16  org.python.python             	0x0000000107bee0f9 run_mod + 103
17  org.python.python             	0x0000000107bee277 pyrun_file + 216
18  org.python.python             	0x0000000107bec925 PyRun_SimpleFileExFlags + 671
19  org.python.python             	0x0000000107c04844 Py_RunMain + 1836
20  org.python.python             	0x0000000107c04ba0 pymain_main + 370
21  org.python.python             	0x0000000107c04bf5 Py_BytesMain + 42
22  libdyld.dylib                 	0x00007fff6a8633d5 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff6a998332 swtch_pri + 10
1   libsystem_pthread.dylib       	0x00007fff6aa59e90 sched_yield + 11
2   libopenblas64_.0.dylib        	0x0000000108b1d44b blas_thread_server + 123
3   libsystem_pthread.dylib       	0x00007fff6aa572eb _pthread_body + 126
4   libsystem_pthread.dylib       	0x00007fff6aa5a249 _pthread_start + 66
5   libsystem_pthread.dylib       	0x00007fff6aa5640d thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007ffe00000002  rbx: 0x00007feaf1e08600  rcx: 0x0000000111e3b4f4  rdx: 0x00007ffdffffffff
  rdi: 0x0000000000000003  rsi: 0x0000000111691110  rbp: 0x00007ffee81258a0  rsp: 0x00007ffee8125608
   r8: 0x0000000111e3b500   r9: 0x0000000111e3b560  r10: 0x00007feaf1e08600  r11: 0x00007feaf1c50d70
  r12: 0x00000001116911a0  r13: 0x0000000111e3b520  r14: 0x00007ffee812567c  r15: 0x0000000111e3b4fc
  rip: 0x0000000112527d69  rfl: 0x0000000000010206  cr2: 0x00007fff11691112
  
Logical CPU:     1
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x107ad9000 -        0x107adafff +org.python.python (3.9.2 - 3.9.2) <781BC08C-36F6-3C88-B064-121C31483819> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
       0x107ae3000 -        0x107cdfff7 +org.python.python (3.9.2, [c] 2001-2019 Python Software Foundation. - 3.9.2) <44DAC685-2ED8-3C62-86EC-0A62970FD395> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/Python
       0x107e2a000 -        0x107e32ff7 +libintl.8.dylib (0) <9FE2A5C0-399B-3E88-A1B0-45932549E276> /opt/local/lib/libintl.8.dylib
       0x107e3d000 -        0x107f31ff3 +libiconv.2.dylib (0) <4C522CA5-5A0C-3028-96B5-824E03D7ABE7> /opt/local/lib/libiconv.2.dylib
       0x108197000 -        0x1081a6ff7 +_ctypes.cpython-39-darwin.so (0) <06B05AF3-2C09-3B0F-A49E-3ABDFA15A1BF> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
       0x1081b8000 -        0x1081bdfd7 +libffi.7.dylib (0) <51F1217E-AB65-3FFC-B5F3-8137CC538B91> /opt/local/lib/libffi.7.dylib
       0x1081c1000 -        0x1081c6fff +_struct.cpython-39-darwin.so (0) <990C202E-8131-3F1F-A1AF-A2E3AEE01FE8> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_struct.cpython-39-darwin.so
       0x10828f000 -        0x108292ff3 +_heapq.cpython-39-darwin.so (0) <48E0A9AB-3D35-3C71-9FD4-7928E3DD279D> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_heapq.cpython-39-darwin.so
       0x1082d6000 -        0x1082dbff3 +_json.cpython-39-darwin.so (0) <C76A06CD-6121-31AB-829F-9141C8D539CD> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_json.cpython-39-darwin.so
       0x1082e0000 -        0x1086a7ff3 +_multiarray_umath.cpython-39-darwin.so (0) <94CED9BB-90B1-35C1-98BC-BBAA801637CC> /Users/USER/Documents/*/_multiarray_umath.cpython-39-darwin.so
       0x1087ec000 -        0x10c475b47 +libopenblas64_.0.dylib (0) <10431D8F-5E3B-3BBC-ABD5-81F6A73A5269> /Users/USER/Documents/*/libopenblas64_.0.dylib
       0x10c730000 -        0x10c847ff7 +libgfortran.3.dylib (0) <9ABE5EDE-AD43-391A-9E54-866711FAC32A> /Users/USER/Documents/*/libgfortran.3.dylib
       0x10c8b4000 -        0x10c8eafff +libquadmath.0.dylib (0) <7FFA409F-FB04-3B64-BE9A-3E3A494C975E> /Users/USER/Documents/*/libquadmath.0.dylib
       0x10c8fe000 -        0x10c913ff7 +libgcc_s.1.dylib (0) <7C6D7CB7-82DB-3290-8181-07646FEA1F80> /Users/USER/Documents/*/libgcc_s.1.dylib
       0x10e963000 -        0x10e96aff3 +math.cpython-39-darwin.so (0) <CD8CF33F-38D8-3C2F-A82C-86D39E70917C> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/math.cpython-39-darwin.so
       0x10e971000 -        0x10e97dff7 +_datetime.cpython-39-darwin.so (0) <EE198872-CD15-371B-939D-7428FC4923C8> /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_datetime.cpython-39-darwin.so
       0x10ea93000 -  [...]

2022-01-21 20:41 UTC, morteham commented
Looks like a problem with the character length. I will try to get a Mac to debug the problem.

2022-01-21 20:43 UTC, vegardjervell commented
That sounds reasonable, thank you!

2022-01-24 20:11 UTC, morteham commented
From the issue report it looks like you have GCC version 11.2.0 installed. Strange that version 4.2.1 is reported by `gcc -dumpfullversion -dumpversion`. What is the full output from the command `gcc --version`?

2022-01-24 20:56 UTC, vegardjervell commented
output from `gcc --version` appears to refer to the 4.2.1 version, 

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Looking a bit closer, I appear to have quite a few gcc installations lying around... Both gcc 6.5.0 and 11.2.0 from homebrew and 6.3.0 installed together with gfortran, as well as 4.2.1 installed with Xcode. This is more than likely of a result of me learning along the way and not having cleaned up enough as I have moved forward.

I guess the issue is that different versions may have been called at different times, in that case this shouldn't be an issue for someone with a bit more experience and better overview of what they have installed.

2022-01-25 11:53 UTC, morteham commented
We probably should have a better test for the GCC major version, but for now I close the PR and the issue. If I come across a better way of thesting this I will update the code.

2022-01-25 14:00 UTC, vegardjervell commented
Sounds good, it isn't hard to fix it locally either now that the reason is known. Thank you :)

2022-02-02 13:05 UTC, lervag requested changes
I think this is more or less ready, but with a few comments. If you don't mind I can just make the suggested changes.

2022-02-02 13:05 UTC, lervag commented on addon/pycThermopack/pyctp/utils.py
> +        out = check_output(["gcc", "-dumpfullversion", "-dumpversion"])
Why both flags? Does it not suffice with `-dumpfullversion`?

2022-02-02 13:21 UTC, lervag commented
I've pushed a commit with my suggested changes now.

2022-02-02 13:21 UTC, lervag approved these changes

2022-02-02 14:55 UTC, morteham commented on addon/pycThermopack/pyctp/utils.py
> +        out = check_output(["gcc", "-dumpfullversion", "-dumpversion"])
For some reason using only `-dumpfullversion`  did not work with MacOS. Googling I found a post that stated using both flags should work consistently with "all" platforms.

2022-02-02 17:36 UTC, lervag commented on addon/pycThermopack/pyctp/utils.py
> +        out = check_output(["gcc", "-dumpfullversion", "-dumpversion"])
Ok; I've reverted my change here to include both.

2022-02-07 06:47 UTC, lervag commented
I would think this is ready for merge?

2022-02-07 07:19 UTC, merged